### ISSUE TITLE
Quality of the Final Classification

### ISSUE THREAD

**Issue by Oktai15** [IBM/BAGAN#1]
@stevemart @ova-mariani Great paper, thank you!

Can you provide results of "Quality of the Final Classification" not only as figures but also with just numbers? It will be cool to get results, for example, in CSV, for every cases GAN, ACGAN, BAGAN, Plain and Mirror.

**Comment by ova-mariani** [comment]
Hi Oktai!
Thanks for your interest!

[summary_min_GTSRB_64--release.xlsx](https://github.com/IBM/BAGAN/files/2382696/summary_min_GTSRB_64--release.xlsx)

Here the results for GTSRB.
