### ISSUE TITLE
Problem with initialisation of GAN.

### ISSUE THREAD

**Issue by siddharthdivi** [IBM/BAGAN#2]
After the line, " print("BAGAN autoenc initialized, init gan") ", when the function self.init_gan() is called, an error occurs. The error occurs because it goes into the except block of the init_gan() function, the reason being, the function " self._get_lst_bck_name () " returns None. 

Is this supposed to happen? As of now, I've just called the self.backup_point(0) to initialize the weights of the GAN. Is this alright ? This is just initialisation of the GAN right?

**Comment by ova-mariani** [comment]
It seems to have something to do with model saving and reloading.

If you train with the bagan_train.py script, a directory to store results including models should be automatically create `res_<datasetname>_dmode_<dmode>_gmode_<gmode>_unbalance_<unbalance>_epochs_<epochs>_lr_<learningrate>_seed_<seed>`, is it?

Please send me more info about how you run the code to help me understanding what generates the issue.
