### ISSUE TITLE
Is normalization for CIFAR10 correct?

### ISSUE THREAD

**Issue by ptran1203** [IBM/BAGAN#9]
Hi,
Thank for your great work!

I would like to correct a little bit

In BatchGenerator you normalize the images by
`img = img / 255 - 0.5`

but in function _save_image_array()_ , you recover it by
`img = (img * 127.5 + 127.5).astype(np.uint8)`

it leads to a little difference.
 - image from generator
![image](https://user-images.githubusercontent.com/36766404/74456234-1404da00-4eb9-11ea-9862-e1261b86dbab.png)
 - image from dataset
![image](https://user-images.githubusercontent.com/36766404/74456253-1a935180-4eb9-11ea-9f64-6161f74c6f4d.png)

Seems like we want to normalize between -1 and 1
In BatchGenerator It should be: `img = (img - 127.5) / 127.5`

Thanks

**Comment by cristianomalossi** [comment]
Thank you for your bug fix. We have merged into master.
